name: CI
on: [push, pull_request]
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install vcpkg and packages
        uses: lukka/run-vcpkg@v7
        id: runvcpkg
        with:
          vcpkgGitCommitId: d781bd9ca77ac3dc2f13d88169021d48459c665f
          vcpkgTriplet: 'arm64-windows'
          vcpkgArguments: 'tomlplusplus'
